### ISSUE TITLE
Bug report (not sure why or how this happened, but some safeguard needs to be put in)

### ISSUE THREAD

**Issue by iarbak** [sgpthomas/trails#10]
01/04 15:26:16: Launching app
Cold swapped changes.
$ adb shell am start -n "com.ksatgames.trails/com.ksatgames.trails.Start" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 13150 on device motorola-xt1033-TA93402K7U
I/art: Late-enabling -Xcheck:jni
I/InstantRun: Instant Run Runtime started. Android package is com.ksatgames.trails, real application class is null.
W/art: Failed to find OatDexFile for DexFile /data/data/com.ksatgames.trails/files/instant-run/dex/slice-slice_9-classes.dex ( canonical path /data/data/com.ksatgames.trails/files/instant-run/dex/slice-slice_9-classes.dex) with checksum 0x9a2107ba in OatFile /data/data/com.ksatgames.trails/cache/slice-slice_9-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/com.ksatgames.trails/files/instant-run/dex/slice-slice_4-classes.dex ( canonical path /data/data/com.ksatgames.trails/files/instant-run/dex/slice-slice_4-classes.dex) with checksum 0xf35e0479 in OatFile /data/data/com.ksatgames.trails/cache/slice-slice_4-classes.dex
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas: Validating map...
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.016_msm8226_LA.BF.1.1.1_RB1__release_AU ()
              OpenGL ES Shader Compiler Version: E031.25.03.00
              Build Date: 02/11/15 Wed
              Local Branch: 
              Remote Branch: quic/LA.BF.1.1.1_rb1.10
              Local Patches: NONE
              Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.016 + 62ca4eb + acd831d + 9f8b442 + e027a02 + cba30ba + 53c303a + a649d79 + 23e16f8 + 5e97da7 + cbd2a44 + 33d072a + 7aacf06 + 72b33e7 + 28f6f60 + b4c13d8 +  NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Enabling debug mode 0
E/AndroidRuntime: FATAL EXCEPTION: Thread-56909
                  Process: com.ksatgames.trails, PID: 13150
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawColor(int)' on a null object reference
                      at come.ksatgame.trails.gameEngine.GameView.draw(GameView.java:309)
                      at come.ksatgame.trails.gameEngine.GameView.run(GameView.java:171)
                      at java.lang.Thread.run(Thread.java:818)
I/Process: Sending signal. PID: 13150 SIG: 9
Application terminated.

**Comment by iarbak** [comment]
Resolved (i think)
What the problem might have been was draw continued to be called even after the next activity started (at times).
